function getURLWikiCastellanoEquipo(constructorId) {
    const URLWiki = {
        "arrows" : "https://es.wikipedia.org/wiki/Arrows_Grand_Prix_International",
        "bar" : "https://es.wikipedia.org/wiki/British_American_Racing",
        "benetton" : "https://es.wikipedia.org/wiki/Benetton_Formula",
        "ferrari" : "https://es.wikipedia.org/wiki/Scuderia_Ferrari",
        "jaguar" : "https://es.wikipedia.org/wiki/Jaguar_Racing",
        "jordan" : "https://es.wikipedia.org/wiki/Jordan_Grand_Prix",
        "mclaren" : "https://es.wikipedia.org/wiki/McLaren",
        "minardi" : "https://es.wikipedia.org/wiki/Minardi",
        "prost" : "https://es.wikipedia.org/wiki/Prost_Grand_Prix",
        "sauber" : "https://es.wikipedia.org/wiki/Sauber",
        "williams" : "https://es.wikipedia.org/wiki/Williams_Grand_Prix_Engineering",
        "renault" : "https://es.wikipedia.org/wiki/Renault_F1_Team",
        "toyota" : "https://es.wikipedia.org/wiki/Toyota_Racing",
        "red_bull" : "https://es.wikipedia.org/wiki/Red_Bull_Racing",
        "bmw_sauber" : "https://es.wikipedia.org/wiki/BMW_Sauber",
        "honda" : "https://es.wikipedia.org/wiki/Honda_Racing_F1_Team",
        "mf1" : "https://es.wikipedia.org/wiki/Midland_F1_Racing",
        "spyker_mf1" : "https://es.wikipedia.org/wiki/Spyker_F1",
        "super_aguri" : "https://es.wikipedia.org/wiki/Super_Aguri_F1",
        "toro_rosso" : "https://es.wikipedia.org/wiki/Scuderia_Toro_Rosso",
        "spyker" : "https://es.wikipedia.org/wiki/Spyker_F1",
        "force_india" : "https://es.wikipedia.org/wiki/Force_India_Formula_One_Team",
        "brawn" : "https://es.wikipedia.org/wiki/Brawn_GP",
        "hrt" : "https://es.wikipedia.org/wiki/Hispania_Racing",
        "lotus_racing" : "https://es.wikipedia.org/wiki/Team_Lotus",
        "mercedes" : "https://es.wikipedia.org/wiki/Mercedes_GP",
        "virgin" : "https://es.wikipedia.org/wiki/Virgin_Racing",
        "caterham" : "https://es.wikipedia.org/wiki/Caterham_F1",
        "lotus_f1" : "https://es.wikipedia.org/wiki/Lotus_F1",
        "marussia" : "https://es.wikipedia.org/wiki/Marussia_F1",
        "manor" : "https://es.wikipedia.org/wiki/Marussia_F1",
        "haas" : "https://es.wikipedia.org/wiki/Haas_F1_Team",
        "alfa" : "https://es.wikipedia.org/wiki/Alfa_Romeo_Racing",
        "racing_point" : "https://es.wikipedia.org/wiki/Racing_Point_F1_Team",
        "alphatauri" : "https://es.wikipedia.org/wiki/Scuderia_AlphaTauri",
        "alpine" : "https://es.wikipedia.org/wiki/Alpine_F1_Team",
        "aston_martin" : "https://es.wikipedia.org/wiki/Aston_Martin_F1_Team",
        "rb" : "https://es.wikipedia.org/wiki/Racing_Bulls_Formula_One_Team",
    };
    return URLWiki[constructorId] || "null";
}

module.exports = { getURLWikiCastellanoEquipo };
