function getPrimeraCarrera(circuitId) {
    const circuitos = {
        "albert_park" : "1966",
        "catalunya" : "1991",
        "hockenheimring" : "1970",
        "hungaroring" : "1986",
        "imola" : "1980",
        "indianapolis" : "1950",
        "interlagos" : "1973",
        "magny_cours" : "1991",
        "monaco" : "1950",
        "monza" : "1950",
        "nurburgring" : "1951",
        "red_bull_ring" : "1997",
        "sepang" : "1999",
        "silverstone" : "1950",
        "spa" : "1950",
        "suzuka" : "1987",
        "villeneuve" : "1978",
        "bahrain" : "2004",
        "shanghai" : "2004",
        "istanbul" : "2005",
        "fuji" : "1976",
        "marina_bay" : "2008",
        "valencia" : "2008",
        "yas_marina" : "2009",
        "yeongam" : "2010",
        "buddh" : "2011",
        "americas" : "2012",
        "sochi" : "2014",
        "rodriguez" : "1963",
        "baku" : "2016",
        "ricard" : "1971",
        "mugello" : "2020",
        "portimao" : "2020",
        "jeddah" : "2021",
        "losail" : "2021",
        "zandvoort" : "1952",
        "miami" : "2022",
        "vegas" : "2023",
    }
    return circuitos[circuitId] || '';
}

function getUltimaCarrera(circuitId) {
    const circuitos = {
        "albert_park" : "2025",
        "catalunya" : "2025",
        "hockenheimring" : "2019",
        "hungaroring" : "2025",
        "imola" : "2025",
        "indianapolis" : "2007",
        "interlagos" : "2025",
        "magny_cours" : "2008",
        "monaco" : "2025",
        "monza" : "2025",
        "nurburgring" : "2020",
        "red_bull_ring" : "2025",
        "sepang" : "2017",
        "silverstone" : "2025",
        "spa" : "2025",
        "suzuka" : "2025",
        "villeneuve" : "2025",
        "bahrain" : "2025",
        "shanghai" : "2025",
        "istanbul" : "2021",
        "fuji" : "2008",
        "marina_bay" : "2025",
        "valencia" : "2012",
        "yas_marina" : "2025",
        "yeongam" : "2013",
        "buddh" : "2013",
        "americas" : "2025",
        "sochi" : "2021",
        "rodriguez" : "2025",
        "baku" : "2025",
        "ricard" : "2022",
        "mugello" : "2020",
        "portimao" : "2021",
        "jeddah" : "2025",
        "losail" : "2025",
        "zandvoort" : "2025",
        "miami" : "2025",
        "vegas" : "2025",
    }
    return circuitos[circuitId] || '';
}

function getLongitudCircuito(circuitId) {
    const circuitos = {
        "albert_park" : "5.278",
        "catalunya" : "4.657",
        "hockenheimring" : "4.574",
        "hungaroring" : "4.381",
        "imola" : "4.909",
        "indianapolis" : "4.192",
        "interlagos" : "4.309",
        "magny_cours" : "4.411",
        "monaco" : "3.337",
        "monza" : "5.793",
        "nurburgring" : "5.144",
        "red_bull_ring" : "4.318",
        "sepang" : "5.543",
        "silverstone" : "5.891",
        "spa" : "7.004",
        "suzuka" : "5.807",
        "villeneuve" : "4.361",
        "bahrain" : "5.412",
        "shanghai" : "5.451",
        "istanbul" : "5.338",
        "fuji" : "4.563",
        "marina_bay" : "4.940",
        "valencia" : "5.419",
        "yas_marina" : "5.281",
        "yeongam" : "5.615",
        "buddh" : "5.125",
        "americas" : "5.513",
        "sochi" : "5.848",
        "rodriguez" : "4.304",
        "baku" : "6.003",
        "ricard" : "5.842",
        "mugello" : "5.245",
        "portimao" : "4.653",
        "jeddah" : "6.174",
        "losail" : "5.419",
        "zandvoort" : "4.259",
        "miami" : "5.412",
        "vegas" : "6.201",
    }
    return circuitos[circuitId] || '';
}

function getVueltas(circuitId) {
    const circuitos = {
        "albert_park" : "58",
        "catalunya" : "66",
        "hockenheimring" : "67",
        "hungaroring" : "70",
        "imola" : "63",
        "indianapolis" : "56",
        "interlagos" : "71",
        "magny_cours" : "70",
        "monaco" : "78",
        "monza" : "53",
        "nurburgring" : "60",
        "red_bull_ring" : "71",
        "sepang" : "56",
        "silverstone" : "52",
        "spa" : "44",
        "suzuka" : "53",
        "villeneuve" : "70",
        "bahrain" : "57",
        "shanghai" : "56",
        "istanbul" : "58",
        "fuji" : "53",
        "marina_bay" : "61",
        "valencia" : "57",
        "yas_marina" : "55",
        "yeongam" : "55",
        "buddh" : "60",
        "americas" : "56",
        "sochi" : "53",
        "rodriguez" : "71",
        "baku" : "51",
        "ricard" : "53",
        "mugello" : "59",
        "portimao" : "66",
        "jeddah" : "50",
        "losail" : "57",
        "zandvoort" : "72",
        "miami" : "57",
        "vegas" : "50",
    }
    return circuitos[circuitId] || '';
}

function getRecordPista(circuitId) {
    const circuitos = {
        "albert_park" : "Charles Leclerc 1:19:813 (2024)",
        "catalunya" : "Max Verstappen 1:16:330 (2023)",
        "hockenheimring" : "Kimi Raikkonen 1:13:780 (2004)",
        "hungaroring" : "Lewis Hamilton 1:16:627 (2020)",
        "imola" : "Lewis Hamilton 1:15:484 (2020)",
        "indianapolis" : "Rubens Barrichello 1:10:399 (2004)",
        "interlagos" : "Valtteri Bottas 1:10:540 (2018)",
        "magny_cours" : "Michael Schumacher 1:15:377 (2004)",
        "monaco" : "Lewis Hamilton 1:12:909 (2021)",
        "monza" : "Rubens Barrichello 1:21:046 (2004)",
        "nurburgring" : "Max Versatppen 1:28:139 (2020)",
        "red_bull_ring" : "Carlos Sainz 1:05:619 (2020)",
        "sepang" : "Sebastian Vettel 1:34:080 (2017)",
        "silverstone" : "Max Versatppen 1:27:097 (2020)",
        "spa" : "Valtteri Bottas 1:46:286 (2018)",
        "suzuka" : "Lewis Hamilton 1:30:983 (2019)",
        "villeneuve" : "Valtteri Bottas 1:13:078 (2019)",
        "bahrain" : "Pedro de la Rosa 1:31:447 (2005)",
        "shanghai" : "Michael Schumacher 1:32:238 (2004)",
        "istanbul" : "Juan Pablo Montoya 1:24:770 (2005)",
        "fuji" : "Felipe Massa 1:18:426 (2008)",
        "marina_bay" : "Daniel Ricciardo 1:34:486 (2024)",
        "valencia" : "Timo Glock 1:38:683 (2009)",
        "yas_marina" : "Max Versatppen 1:26:103 (2021)",
        "yeongam" : "Sebastian Vettel 1:39:605 (2011)",
        "buddh" : "Sebastian Vettel 1:27:249 (2011)",
        "americas" : "Charles Leclerc 1:36:169 (2019)",
        "sochi" : "Lewis Hamilton 1:35:761 (2019)",
        "rodriguez" : "Valtteri Bottas 1:17:774 (2021)",
        "baku" : "Charles Leclerc 1:43:009 (2019)",
        "ricard" : "Sebastian Vettel 1:32:740 (2019)",
        "mugello" : "Lewis Hamilton 1:18:833 (2020)",
        "portimao" : "Lewis Hamilton 1:18:750 (2020)",
        "jeddah" : "Lewis Hamilton 1:30:734 (2021)",
        "losail" : "Lando Norris 1:22:384 (2024)",
        "zandvoort" : "Lewis Hamilton 1:11:097 (2021)",
        "miami" : "Max Verstappen 1:29:708 (2023)",
        "vegas" : "Lando Norris 1:34:876 (2024)",
    }
    return circuitos[circuitId] || '';
}

function getURLStats(circuitId) {
    const circuit = {
        "albert_park" : "https://www.statsf1.com/es/circuit-melbourne/stats-victoire.aspx",
        "catalunya" : "https://www.statsf1.com/es/circuit-barcelone/stats-victoire.aspx",
        "hockenheimring" : "https://www.statsf1.com/es/circuit-hockenheim/stats-victoire.aspx",
        "hungaroring" : "https://www.statsf1.com/es/circuit-hungaroring/stats-victoire.aspx",
        "imola" : "https://www.statsf1.com/es/circuit-imola/stats-victoire.aspx",
        "indianapolis" : "https://www.statsf1.com/es/circuit-indianapolis/stats-victoire.aspx",
        "interlagos" : "https://www.statsf1.com/es/circuit-interlagos/stats-victoire.aspx",
        "magny_cours" : "https://www.statsf1.com/es/circuit-magny-cours/stats-victoire.aspx",
        "monaco" : "https://www.statsf1.com/es/circuit-monaco/stats-victoire.aspx",
        "monza" : "https://www.statsf1.com/es/circuit-monza/stats-victoire.aspx",
        "nurburgring" : "https://www.statsf1.com/es/circuit-nurburgring/stats-victoire.aspx",
        "red_bull_ring" : "https://www.statsf1.com/es/circuit-spielberg/stats-victoire.aspx",
        "sepang" : "https://www.statsf1.com/es/circuit-kuala-lumpur/stats-victoire.aspx",
        "silverstone" : "https://www.statsf1.com/es/circuit-silverstone/stats-victoire.aspx",
        "spa" : "https://www.statsf1.com/es/circuit-spa-francorchamps/stats-victoire.aspx",
        "suzuka" : "https://www.statsf1.com/es/circuit-suzuka/stats-victoire.aspx",
        "villeneuve" : "https://www.statsf1.com/es/circuit-montreal/stats-victoire.aspx",
        "bahrain" : "https://www.statsf1.com/es/circuit-sakhir/stats-victoire.aspx",
        "shanghai" : "https://www.statsf1.com/es/circuit-shanghai/stats-victoire.aspx",
        "istanbul" : "https://www.statsf1.com/es/circuit-istanbul/stats-victoire.aspx",
        "fuji" : "https://www.statsf1.com/es/circuit-fuji/stats-victoire.aspx",
        "marina_bay" : "https://www.statsf1.com/es/circuit-singapour/stats-victoire.aspx",
        "valencia" : "https://www.statsf1.com/es/circuit-valencia/stats-victoire.aspx",
        "yas_marina" : "https://www.statsf1.com/es/circuit-yas-marina/stats-victoire.aspx",
        "yeongam" : "https://www.statsf1.com/es/circuit-yeongam/stats-victoire.aspx",
        "buddh" : "https://www.statsf1.com/es/circuit-new-delhi/stats-victoire.aspx",
        "americas" : "https://www.statsf1.com/es/circuit-austin/stats-victoire.aspx",
        "sochi" : "https://www.statsf1.com/es/circuit-sotchi/stats-victoire.aspx",
        "rodriguez" : "https://www.statsf1.com/es/circuit-mexico-city/stats-victoire.aspx",
        "baku" : "https://www.statsf1.com/es/circuit-bakou/stats-victoire.aspx",
        "ricard" : "https://www.statsf1.com/es/circuit-le-castellet/stats-victoire.aspx",
        "mugello" : "https://www.statsf1.com/es/circuit-mugello/stats-victoire.aspx",
        "portimao" : "https://www.statsf1.com/es/circuit-portimao/stats-victoire.aspx",
        "jeddah" : "https://www.statsf1.com/es/circuit-djeddah/stats-victoire.aspx",
        "losail" : "https://www.statsf1.com/es/circuit-losail/stats-victoire.aspx",
        "zandvoort" : "https://www.statsf1.com/es/circuit-zandvoort/stats-victoire.aspx",
        "miami" : "https://www.statsf1.com/es/circuit-miami/stats-victoire.aspx",
        "vegas" : "https://www.statsf1.com/es/circuit-las-vegas/stats-victoire.aspx",
    }
    return circuit[circuitId] || '';
}

module.exports = {
    getPrimeraCarrera,
    getUltimaCarrera,
    getLongitudCircuito,
    getVueltas,
    getRecordPista,
    getURLStats
};